#!/bin/bash -u

export isDirty;

function isDirtyDirectory()
{
  isDirty="false"
  gitStatus=$(git status)
  if [[ ${gitStatus} =~ "Your branch is ahead" ]]; then
    isDirty="true"
  fi
  if [[ ${gitStatus} =~ "Changes not staged" ]]; then
    isDirty="true"
  fi
  if [[ ${gitStatus} =~ "Changes to be committed" ]]; then
    isDirty="true"
  fi
  if [[ ${gitStatus} =~ "Untracked files" ]]; then
    isDirty="true"
  fi
}
function main()
{
  isDirtyDirectory

  if [[ ${isDirty} == "true" ]]; then
    echo "$(pwd)"
  fi

  exit 0
}

main "$@"
