#!/bin/bash -u

export isDirty;

function isDirtyDirectory()
{
  isDirty="false"
  gitStatus=$(git status)
  if [[ ${gitStatus} =~ "Your branch is ahead" ]]; then
    isDirty="true"
  fi
  if [[ ${gitStatus} =~ "Changes not staged" ]]; then
    isDirty="true"
  fi
  if [[ ${gitStatus} =~ "Changes to be committed" ]]; then
    isDirty="true"
  fi
}
function main()
{
  # get all the directory paths that contain a '.git' directory
  gitDirectories=( $(find . -type d -name ".git" -exec dirname {} \; ) )

  for directory in "${gitDirectories[@]}"; do
    (
      cd "${directory}"

      isDirtyDirectory
      if [[ ${isDirty} == "true" ]]; then
        echo "$(pwd)"
      fi
    )
  done
  exit 0
}

main "$@"
